---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: devops-nginx
  name: devops-nginx
spec:
  ports:
    # port that this service should serve on
    - port: 80
      # the service will be accessible from the outside on this port
      nodePort: 31000
      protocol: TCP
  # label keys and values that must match in order to receive traffic for this service
  selector:
    run: devops-nginx
  type: NodePort
